In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.model_selection import GridSearchCV, cross_validate, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectFromModel
from sklearn.decomposition import PCA
import statsmodels.api as sm
from statsmodels.imputation.mice import MICE, MICEData
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.optimizers import SGD
from keras.utils import to_categorical
from keras.constraints import maxnorm
from matplotlib import pyplot
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.impute import SimpleImputer
import time
from collections import Counter
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.experimental import enable_iterative_imputer 
from sklearn.impute import IterativeImputer
from sklearn.neural_network import MLPClassifier
import itertools
#import all the functions we wrote ourselves
%pip install import_ipynb
import import_ipynb
#import Functions as functions

ModuleNotFoundError: No module named 'keras'

In [145]:
#importing the datasets
#index_col=0 to make the companies/ the dates the indizes

df14=pd.read_csv("C:/Users/eminu/OneDrive/Desktop/GIT/Project/2014_Financial_Data.csv",sep=",",index_col=0)
df15=pd.read_csv("C:/Users/eminu/OneDrive/Desktop/GIT/Project/2015_Financial_Data.csv",sep=",",index_col=0)
df16=pd.read_csv("C:/Users/eminu/OneDrive/Desktop/GIT/Project/2016_Financial_Data.csv",sep=",",index_col=0)
df17=pd.read_csv("C:/Users/eminu/OneDrive/Desktop/GIT/Project/2017_Financial_Data.csv",sep=",",index_col=0)
df18=pd.read_csv("C:/Users/eminu/OneDrive/Desktop/GIT/Project/2018_Financial_Data.csv",sep=",",index_col=0)

In [146]:
#importing the dataset with the s&p performances

sp=pd.read_csv("C:/Users/eminu/OneDrive/Desktop/GIT/Project/sp-500-historical-annual-returns.csv",sep=",",index_col=0)

In [158]:
#pipelines:
from sklearn.pipeline import Pipeline as pl

In [147]:
#creating the values with the perf. of the s&p to compare the companies to

sp14_performance=sp.loc["2014-12-31"]
sp15_performance=sp.loc["2015-12-31"]
sp16_performance=sp.loc["2016-12-30"]
sp17_performance=sp.loc["2017-12-29"]
sp18_performance=sp.loc["2018-12-31"]

In [148]:
#using encoder to make the categorical vars as that will still work when using the pipeline
from sklearn import preprocessing as pp

all_data=[df14,df15,df16,df17,df18]

le=pp.LabelEncoder()

for data in all_data:
    data["Sector"]=le.fit_transform(data["Sector"])

In [149]:
#creating year variable
all_data=[df14,df15,df16,df17,df18]

count=0
for data in all_data:
    data["year"]=2014+count
    count+=1
    
#converting to cat. variable

all_data=[df14,df15,df16,df17,df18]

for data in all_data:
    data["year"]=data.year.astype("category")

data["year"]

CMCSA    2018
KMI      2018
INTC     2018
MU       2018
GE       2018
         ...
YRIV     2018
YTEN     2018
ZKIN     2018
ZOM      2018
ZYME     2018
Name: year, Length: 4392, dtype: category
Categories (1, int64): [2018]

In [151]:
#making one column with price var

df14.rename(columns={"2015 PRICE VAR [%]": "PRICE_VAR"},inplace=True)
df15.rename(columns={"2016 PRICE VAR [%]": "PRICE_VAR"},inplace=True)
df16.rename(columns={"2017 PRICE VAR [%]": "PRICE_VAR"},inplace=True)
df17.rename(columns={"2018 PRICE VAR [%]": "PRICE_VAR"},inplace=True)
df18.rename(columns={"2019 PRICE VAR [%]": "PRICE_VAR"},inplace=True)

In [160]:
#combining the datasets with an outer join to make a huge df

df=pd.concat([df14,df15,df16,df17,df18])
df.shape
df

,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,Earnings before Tax,...,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,PRICE_VAR,Class,year
PG,7.440100e+10,-0.0713,3.903000e+10,3.537100e+10,0.000000e+00,2.146100e+10,2.146100e+10,1.391000e+10,7.090000e+08,1.449400e+10,...,-0.0217,0.0359,0.0316,0.1228,0.0000,-0.1746,3,-9.323276,0,2014
VIPS,3.734148e+09,1.1737,2.805625e+09,9.285226e+08,1.083303e+08,3.441414e+08,7.939267e+08,1.345959e+08,1.214869e+07,1.753823e+08,...,NaN,NaN,NaN,NaN,1.6484,1.7313,3,-25.512193,0,2014
KR,9.837500e+10,0.0182,7.813800e+10,2.023700e+10,0.000000e+00,1.519600e+10,1.751200e+10,2.725000e+09,4.430000e+08,2.270000e+09,...,0.0981,0.1886,0.3268,0.2738,0.0000,0.0234,3,33.118297,1,2014
RAD,2.552641e+10,0.0053,1.820268e+10,7.323734e+09,0.000000e+00,6.561162e+09,6.586482e+09,7.372520e+08,4.245910e+08,2.502180e+08,...,-0.0510,-0.0189,0.1963,-0.0458,0.0000,-0.0060,3,2.752291,1,2014
GIS,1.790960e+10,0.0076,1.153980e+10,6.369800e+09,0.000000e+00,3.474300e+09,3.412400e+09,2.957400e+09,3.024000e+08,2.707700e+09,...,0.0090,0.0215,0.0274,0.1025,0.0000,-0.0220,3,12.897715,1,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YRIV,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000e+00,3.755251e+06,3.755251e+06,-3.755251e+06,1.105849e+07,-1.482451e+07,...,0.0000,-0.0508,-0.1409,-0.0152,0.0000,-0.2602,8,-90.962099,0,2018
YTEN,5.560000e+05,-0.4110,0.000000e+00,5.560000e+05,4.759000e+06,5.071000e+06,9.830000e+06,-9.274000e+06,0.000000e+00,-9.170000e+06,...,0.0000,-0.2323,-0.8602,0.0000,0.0352,-0.0993,0,-77.922077,0,2018
ZKIN,5.488438e+07,0.2210,3.659379e+07,1.829059e+07,1.652633e+06,7.020320e+06,8.672953e+06,9.617636e+06,1.239170e+06,8.416324e+06,...,0.7706,0.2489,0.4074,-0.0968,0.2415,0.8987,0,-17.834400,0,2018
ZOM,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,1.031715e+07,4.521349e+06,1.664863e+07,-1.664863e+07,0.000000e+00,-1.664769e+07,...,0.0000,0.1568,-0.2200,0.0000,2.7499,0.1457,7,-73.520000,0,2018
ZYME,5.301900e+07,0.0243,0.000000e+00,5.301900e+07,5.668400e+07,2.945700e+07,8.614600e+07,-3.312700e+07,1.660000e+05,-3.438500e+07,...,0.0000,0.8519,0.1325,0.0000,0.3577,0.5880,6,209.462222,1,2018

In [198]:
#how many NAs are there and the percentage of missing values
df.isnull().sum().sort_values(ascending=False)/len(df)

#dropping the columns with more than one third of the cells missing
#df.dropna(axis="columns", thresh=(1/3)*len(df))

#plotting some stuff:

cashConversionCycle                           0.999119
operatingCycle                                0.999119
shortTermCoverageRatios                       0.486559
10Y Shareholders Equity Growth (per Share)    0.433630
10Y Net Income Growth (per Share)             0.426863
                                                ...
Financing Cash Flow                           0.044772
Class                                         0.000000
Sector                                        0.000000
PRICE_VAR                                     0.000000
year                                          0.000000
Length: 225, dtype: float64

In [200]:
#do that for all the years
#outliers (saw that in the description)

# Get stocks that increased more than 500%
gain = 200
top_gainers = df[df["PRICE_VAR"] >= gain]
top_gainers = top_gainers["PRICE_VAR"].sort_values(ascending=False)
print(f"{len(top_gainers)} STOCKS with more than {gain}% gain.")

#we have 231 stocks with more than 200% gain

#we do not want these stocks as we think that they are "faked" (or typos etc.)

df = df.drop(top_gainers.index)

114 STOCKS with more than 200% gain.

In [201]:
# calculates the buy/hold/sell-signal based on excess return vs. sp500
# buy: excess return >= 2.5
# hold: 2.5 > excess return > -2.5
# sell: -2.5 >= excess return

all_data = [df14, df15, df16, df17, df18]

for data in all_data:
    data["buy"] = np.where((data["PRICE_VAR"].subtract(sp14_performance)) >= 2.5, [1], [0])
    data["hold"] = np.where((data["PRICE_VAR"].subtract(sp14_performance) < 2.5) &
                        (data["PRICE_VAR"].subtract(sp14_performance) > -2.5), [1], [0])
    data["sell"] = np.where((data["PRICE_VAR"].subtract(sp14_performance)) <= -2.5, [1], [0])
    

df14[["buy", "hold", "sell"]].head()

ValueError: Length of values (3809) does not match length of index (3808)